name: build

on:
  release:
    types: [published]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout the release tag
        uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: built
          path: .

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [build]
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: built
      - name: Publish
        working-directory: built
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish
